Add packages for testing Firestore, enabling multiDex, localization,…
mutairibassam/tamini pull request #19
Opened 2023-09-30 15:20 UTC by HamadAlharbi1

… and OTP input

In this commit:
- Added Firestore package for database testing
- Enabled multiDex and set minSdkVersion to 21 to fix a bug
- Included localization package for supporting multiple languages
- Integrated pin_input_text_field package for OTP input

These changes aim to enhance database testing, resolve a bug related to multiDex, support localization, and implement an OTP input field in the app.

2023-10-01 05:11 UTC, mutairibassam requested changes

2023-10-01 05:11 UTC, mutairibassam commented on lib/pages/registration_page.dart
> +                  MaterialPageRoute(builder: (context) => const RegistrationPage()),
Navigation should be directed to `login page`. For testing make a new empty page with login name (even if you are not going to handle it) since login page has crossed with your logic.

2023-10-01 05:11 UTC, mutairibassam commented on lib/pages/registration_page.dart
> +              if (otp == '1234') {
Always write a valid logic and for bypassing use `kDebugMode`.
```suggestion
            onOtpEntered: (otp) {
              // Handle the OTP verification logic here
              if (kDebugMode) {
```

2023-10-01 05:38 UTC, HamadAlharbi1 commented on android/app/build.gradle
> +        multiDexEnabled true
Ok ,Done

2023-10-01 07:54 UTC, HamadAlharbi1 commented on lib/components/custom_button.dart
> +class CustomButton extends StatelessWidget {
In fact I will use this widget many times so that I suggest this name ,

2023-10-01 07:54 UTC, HamadAlharbi1 commented on lib/components/custom_text_field.dart
> +class CustomTextField extends StatefulWidget {
In fact I will use this widget many times so that I suggest this name ,

2023-10-01 07:55 UTC, HamadAlharbi1 commented on lib/pages/registration_page.dart
> +                  MaterialPageRoute(builder: (context) => const RegistrationPage()),
ok done

2023-10-01 08:07 UTC, HamadAlharbi1 commented on lib/app.dart
> +  }
i thing its not used right now  , so that i removed

2023-10-01 21:07 UTC, HamadAlharbi1 commented on lib/app.dart
> +    localization.onTranslatedLanguage = _onTranslatedLanguage;
done

2023-10-02 04:28 UTC, mutairibassam commented on lib/components/custom_button.dart
> +class CustomButton extends StatelessWidget {
Widget reusability does not mean it's custom. Custom means the widget should be adaptive to "any shape and behavior".

However, we will revisit this again later. Keep a note please.

2023-10-02 04:28 UTC, mutairibassam commented on lib/components/custom_text_field.dart
> +class CustomTextField extends StatefulWidget {
Widget reusability does not mean it's custom. Custom means the widget should be adaptive to "any shape and behavior".

However, we will revisit this again later. Keep a note please.

2023-10-02 12:56 UTC, merged

2023-10-02 13:03 UTC, mutairibassam commented
reference #2 #4