User/tracking/requests
mutairibassam/tamini pull request #29
Opened 2023-10-05 22:38 UTC by HamadAlharbi1

2023-10-06 22:07 UTC, mutairibassam requested changes

2023-10-06 22:07 UTC, mutairibassam commented on lib/pages/request_quotations_page.dart
> +    final requestId = const Uuid().v4();
request id shouldn't be randomly generated due to id conflict. request id should be incremented by one starting from 1000.

2023-10-06 22:07 UTC, mutairibassam commented on lib/pages/request_quotations_page.dart
> +        'requestType': "Request_Quotations",
Request type should be written as enums to unify types and avoid typos. Moreover, it should be simplified either using numbers [1,2,3,4] or [quotation, ...] without request.

2023-10-06 22:07 UTC, mutairibassam commented on lib/pages/tracking_requests.dart
> +        FirebaseFirestore.instance.collection('RequestQuotations').where('userId', isEqualTo: '$uid').snapshots();
```suggestion
        FirebaseFirestore.instance.collection('quotations').where('userId', isEqualTo: '$uid').snapshots();
```

2023-10-06 22:07 UTC, mutairibassam commented on pubspec.yaml
> +    uuid: ^4.1.0
missing docs.

2023-10-07 08:56 UTC, HamadAlharbi1 commented on lib/app.dart
> +}
i try this but its not working ..

2023-10-07 08:58 UTC, HamadAlharbi1 commented on lib/app.dart
> +      home: buildFirstWidget(),
name changed  to  checkUserAuthentication

2023-10-07 10:43 UTC, HamadAlharbi1 commented on pubspec.yaml
> +    uuid: ^4.1.0
done

2023-10-07 10:43 UTC, HamadAlharbi1 commented on lib/pages/request_quotations_page.dart
> +    final requestId = const Uuid().v4();
done

2023-10-07 10:44 UTC, HamadAlharbi1 commented on lib/pages/request_quotations_page.dart
> +  }
done

2023-10-07 10:44 UTC, HamadAlharbi1 commented on lib/pages/registration_page.dart
> +                ),
done

2023-10-07 10:44 UTC, HamadAlharbi1 commented on lib/pages/registration_page.dart
> +  }
done

2023-10-07 10:44 UTC, HamadAlharbi1 commented on lib/pages/home_page.dart
> +                text: "Tracking_Requests".i18n()),
done

2023-10-07 10:57 UTC, HamadAlharbi1 commented on lib/pages/tracking_requests.dart
> +        FirebaseFirestore.instance.collection('RequestQuotations').where('userId', isEqualTo: '$uid').snapshots();
done

2023-10-07 12:11 UTC, mutairibassam requested changes

2023-10-07 20:35 UTC, merged