Creation/quotation/service/class
mutairibassam/tamini pull request #30
Opened 2023-10-09 13:21 UTC by HamadAlharbi1

2023-10-09 15:51 UTC, mutairibassam requested changes

2023-10-09 15:51 UTC, mutairibassam commented on lib/common/quotation_service.dart
> +  }
All methods associated with this class is `static` which defeat the purpose of having class in this case.

2023-10-09 15:51 UTC, mutairibassam commented on lib/common/quotation_service.dart
> +      int newRequestId = currentRequestId + 1;
based on my understanding you are fetching collection `metadata` first just to get last request number and increment it by one.

Are you fetching all documents or only last added one?

2023-10-09 15:51 UTC, mutairibassam commented on lib/common/quotation_service.dart
> +      });
instead of having 2 different http requests, you might get the last id and update it within the same request. I know something similar doable in mongodb. Check if firebase support update document.

example;
```suggestion
      /// below code is just for explanation, not valid.
      FirebaseDocument doc = await FirebaseFirestore.instance.collection('metadata').doc('requestId');
      firebase.update("requestId", doc.requestId.value + 1);
```

2023-10-09 15:51 UTC, mutairibassam commented on lib/components/quotations/quotation_card.dart
> +          widget.request.status == 'sent_awaiting_approval'
status should be defined as `enum`.
```suggestion
          enum requestStatus = {pending, approved, cancelled}
          widget.request.status == requestStatus.pending
```

2023-10-09 16:26 UTC, HamadAlharbi1 commented on lib/common/quotation_service.dart
> +  }
i reuse updateQuotation method three times  in QuotationCard & UpdateQuotationCardItem classes  so that i creat QuotationService  class .

2023-10-09 16:31 UTC, HamadAlharbi1 commented on lib/common/quotation_service.dart
> +      int newRequestId = currentRequestId + 1;
i call only last added one

2023-10-09 16:48 UTC, mutairibassam commented on lib/common/quotation_service.dart
> +      int newRequestId = currentRequestId + 1;
let's try to create 5 different requests from different devices and ensure the id will not be broken.

2023-10-09 16:50 UTC, mutairibassam commented on lib/common/quotation_service.dart
> +  }
I am not asking why did you create a new class, I am asking why did you declare the `methods` such as (updateQuotation) as static.

2023-10-09 17:05 UTC, HamadAlharbi1 commented on lib/common/quotation_service.dart
> +  }
if not i will face this issue 
Instance member 'updateQuotation' can't be accessed using static access.

2023-10-09 17:36 UTC, HamadAlharbi1 commented on lib/common/quotation_service.dart
> +  }
it fixed by define a variable
 QuotationService quotationService = QuotationService();
 
 then access to method like this 
 
 quotationService.updateQuotation(
                            context, widget.request.requestId, {'status': 'approved'}, "approved");

2023-10-09 19:55 UTC, HamadAlharbi1 commented on lib/components/quotations/quotation_card.dart
> +          widget.request.status == 'sent_awaiting_approval'
done

2023-10-10 19:09 UTC, mutairibassam requested changes

2023-10-10 19:09 UTC, mutairibassam commented on lib/components/user_service.dart
> +      timeout: const Duration(seconds: 120),
make it 60 seconds, and give the user an option to re-authenticate.

2023-10-10 19:09 UTC, mutairibassam commented on lib/components/quotations/update_quotation_card.dart
> +                      'status': RequestStatus.pending.toString()
```suggestion
                      'status': RequestStatus.pending.name
```

2023-10-10 19:09 UTC, mutairibassam commented on lib/app.dart
> +                )
We shouldn't pass userId since it's not been used in the home page.

2023-10-10 19:09 UTC, mutairibassam commented on lib/app.dart
> +              );
We should initialize userId within ProfilePage instead of passing it.

2023-10-10 19:29 UTC, HamadAlharbi1 commented on lib/app.dart
> +              );
done

2023-10-10 19:29 UTC, HamadAlharbi1 commented on lib/app.dart
> +                )
done

2023-10-10 19:29 UTC, HamadAlharbi1 commented on lib/components/quotations/update_quotation_card.dart
> +                      'status': RequestStatus.pending.toString()
done

2023-10-10 20:24 UTC, HamadAlharbi1 commented on lib/components/user_service.dart
> +      timeout: const Duration(seconds: 120),
done

2023-10-11 05:55 UTC, mutairibassam commented on lib/common/quotation_service.dart
> +      int newRequestId = currentRequestId + 1;
We can simulate even up to 1000 requests by benchmarking the api.

2023-10-15 07:35 UTC, mutairibassam requested changes

2023-10-15 07:35 UTC, mutairibassam commented on lib/common/quotation_service.dart
> +  }
`showSnackbar` should be placed in `common/util.dart` as it will be used by all components.

2023-10-15 07:35 UTC, mutairibassam commented on lib/common/refund_service.dart
> +  }
`showSnackbar` should be placed in `common/util.dart` as it will be used by all components.

2023-10-15 07:35 UTC, mutairibassam commented on lib/common/user_service.dart
> +  final FirebaseAuth auth = FirebaseAuth.instance;
As you can notice firebase has been initialized in different places, so we can have a singleton class to initialize firebase only one. (optional)

2023-10-15 07:35 UTC, mutairibassam commented on lib/components/quotations/quotation_card.dart
> +  });
Name should be modified to something more descriptive.

2023-10-15 11:11 UTC, HamadAlharbi1 commented on lib/components/quotations/quotation_card.dart
> +  });
done

2023-10-15 11:11 UTC, HamadAlharbi1 commented on lib/common/refund_service.dart
> +  }
done

2023-10-15 11:11 UTC, HamadAlharbi1 commented on lib/common/quotation_service.dart
> +  }
done

2023-10-15 11:12 UTC, HamadAlharbi1 commented on lib/common/quotation_service.dart
> +  Future<void> updateQuotation(context, String requestId, Map<String, dynamic> updates, String massage) async {
done

2023-10-15 11:12 UTC, HamadAlharbi1 commented on lib/common/pic_image.dart
> +        return downloadUrl;
done

2023-10-15 11:12 UTC, HamadAlharbi1 commented on lib/common/pic_image.dart
> +        await uploadTask.whenComplete(() {});
when i try to delete it i faced this issue 

[firebase_storage/object-not-found] No object exists at the desired reference.

2023-10-15 11:13 UTC, HamadAlharbi1 commented on lib/common/pic_image.dart
> +  }
I had a problem when i try to apply that

2023-10-15 11:13 UTC, HamadAlharbi1 commented on lib/common/pic_image.dart
> +  Future<String> selectAndUploadImage(context, String path, String uid) async {
I had a problem when i try to apply that

2023-10-16 06:30 UTC, mutairibassam requested changes

2023-10-16 06:30 UTC, mutairibassam commented on lib/common/user_service.dart
>    }
Dose it return `false` if the user is not exist? it might return null value. Double check.

2023-10-16 06:30 UTC, mutairibassam commented on lib/common/user_service.dart
>    }
This function has nested return statement which will make debugging more challenging and there is no error handling and logging mechanism.

I tried to rewrite the code without testing it. Verify from your side.

```dart
Stream<UserData> streamUserData(String userId) {
  // Create a reference to the Firestore 'users' collection document for the given userId.
  final userDocRef = fireStore.collection('users').doc(userId);

  // Create a stream that listens to changes in the document.
  final userDocStream = userDocRef.snapshots();

  // Map the snapshots to UserData objects and handle potential errors.
  final userDataStream = userDocStream.asyncMap((doc) async {
    if (doc.exists) {
      return UserData.fromMap(doc.data() as Map<String, dynamic>);
    } else {
      throw Exception('User document not found for ID: $userId');
    }
  });

  return userDataStream; //
}
```

2023-10-16 06:30 UTC, mutairibassam commented on lib/i18n/en_US.json
> +	"file_uploaded": "Uploaded ",
space should be removed.
```suggestion
	"file_uploaded": "Uploaded",
```

2023-10-16 07:15 UTC, HamadAlharbi1 commented on lib/common/user_service.dart
>    }
ok its work , thanx

2023-10-16 08:06 UTC, HamadAlharbi1 commented on lib/common/user_service.dart
>    }
ok it fixed 
 Future<bool> userExists(String userId) async {
  DocumentSnapshot doc = await fireStore.collection('users').doc(userId).get();

  if (doc.exists) {
    return true;
  } else {
    return false;
  }
}

2023-10-16 08:13 UTC, mutairibassam commented on lib/common/user_service.dart
>    }
Return type is not specified. Future<bool>

2023-10-16 08:30 UTC, HamadAlharbi1 commented on lib/common/user_service.dart
>    }
Future<bool> userExists(String userId) async {
    DocumentSnapshot doc = await fireStore.collection('users').doc(userId).get();
    if (doc.exists) {
      return true;
    } else {
      return false;
    }
  }
  
  ok its done

2023-10-16 08:34 UTC, HamadAlharbi1 commented on lib/common/user_service.dart
>    }
```suggestion
  Future<bool> userExists(String userId) async {
    DocumentSnapshot doc = await fireStore.collection('users').doc(userId).get();
    if (doc.exists) {
      return true;
    } else {
      return false;
    }
  }
```

actually this is the right code

2023-10-17 09:28 UTC, mutairibassam requested changes

2023-10-17 09:28 UTC, mutairibassam commented on lib/common/user_service.dart
> +                      });
Why navigation to `HomePage` comes before checking if the user is exist or not, and before user creation.

What if (login):
- User is exist but password is wrong.

What if (register):
- User creation request failed.

2023-10-17 09:28 UTC, mutairibassam commented on lib/common/user_service.dart
> +    }
this can be simplified to 
```suggestion
    return await fireStore.collection('users').doc(userId).get().exists;
```

please verify.

2023-10-17 09:28 UTC, mutairibassam commented on lib/components/language_dropdown.dart
> +      },
Since you have a default value, you can use Switch instead of if-else or optimize the if logic. You can check only for 'ar' if not both values will be 'en'.

```dart
if(newValue == 'ar') 
    newLocale = const Locale('ar', 'SA');
else
    newLocale = const Locale('en', 'US');
```

2023-10-17 09:28 UTC, mutairibassam commented on lib/provider/language_provider.dart
> +  }
Code can be optimized

```suggestion
void changeLanguage(Locale locale) async {
  if (_currentLocale != locale) {
    _currentLocale = locale;
    await _saveLocale(locale.languageCode, locale.countryCode);
    notifyListeners();
  }
}
```

Please verify.

2023-10-17 11:10 UTC, HamadAlharbi1 commented on lib/common/user_service.dart
> +    }
i tried to use this code but i faced this issue

The getter 'exists' isn't defined for the type 'Future<DocumentSnapshot<Map<String, dynamic>>>'.
Try importing the library that defines 'exists', correcting the name to the name of an existing getter, or defining a getter or field named 'exists'.

2023-10-17 11:37 UTC, HamadAlharbi1 commented on lib/common/user_service.dart
> +                      });
Why navigation to HomePage comes before checking if the user is exist or not, and before user creation.
 i move it to be inside if statement  thanks for noticing
  , if  User is exist but password is wrong ,User creation request failed. in these cases the error massage will shows  
  
  ``` fixed code 
                     onOtpEntered: (otp) async {
                      FirebaseAuth auth = FirebaseAuth.instance;
                      String smsCode = otp;
                      _credential = PhoneAuthProvider.credential(verificationId: verificationId, smsCode: smsCode);
                      auth.signInWithCredential(_credential).then((result) async {
                        bool exists = await userExists(result.user!.uid);
                        if (!exists) {
                          UserData newUser = UserData(
                            userId: result.user!.uid,
                            userName: 'guest',
                            email: result.user!.email ?? '',
                            phoneNumber: phoneNumber,
                            profilePictureUrl: Constants.profileAvatarUrl,
                            userType: UserType.user.name,
                          );
                          await createUser(newUser);
                          showSnackbar(context, "registration_massage".i18n());
                          context.go('/home_page');
                        } else if (exists) {
                          showSnackbar(context, "login_massage".i18n());
                          context.go('/home_page');
                        }
                      }).catchError((e) {
                        showSnackbar(context, "Invalid_OTP".i18n());
                      });
                    },
```

2023-10-17 11:59 UTC, HamadAlharbi1 commented on lib/components/language_dropdown.dart
> +      },
done

2023-10-17 12:05 UTC, HamadAlharbi1 commented on lib/provider/language_provider.dart
> +  }
done ..

2023-10-17 18:51 UTC, mutairibassam approved these changes
lgtm

2023-10-17 18:52 UTC, merged